# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0006_auto_20161208_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.IntegerField(null=True),
        ),
    ]
