# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0003_student'),
        ('ProjectsApp', '0001_initial'),
        ('CompaniesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('alma_mater', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('projects', models.ManyToManyField(to='ProjectsApp.Project')),
            ],
        ),
    ]
