# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompaniesApp', '0002_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='first_name',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='engineer',
            name='last_name',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
