# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_auto_20161207_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(default='', max_length=120),
        ),
    ]
