# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_auto_20161209_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='project_id',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='project_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
