# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0003_student'),
        ('UniversitiesApp', '0004_auto_20161108_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Subject', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
