# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0006_auto_20161207_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
    ]
