# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0008_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_standing',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
