# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0009_student_class_standing'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='specialty',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
